version: "3.8"

services:
  mysql:
    image: mysql:8.0
    container_name: ctn-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: senha
      MYSQL_DATABASE: todolist
    ports:
      - "3306:3306"
    volumes:
      - db/init.sql:/docker-entrypoint-initdb.d/init.sql
      - mysql_data:/var/lib/mysql

  php:
    image: php:8.2-apache
    container_name: ctn-php
    restart: always
    ports:
      - "8000:80"
    volumes:
      - .:/var/www/html
    depends_on:
      - mysql
    build:
      context: .
      dockerfile: Dockerfile

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: ctn-phpmyadmin
    restart: always
    ports:
      - "8080:80"
    environment:
      PMA_HOST: mysql
      PMA_USER: root
      PMA_PASSWORD: senha
    depends_on:
      - mysql

volumes:
  mysql_data:
